In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import pickle

In [2]:
df=pd.DataFrame(columns=['month','criteria','question','age','ranking'])
df['month'] = np.random.randint(1,12, size=10000)
df['question'] = np.random.randint(1,9, size=10000)
df['age'] = np.random.randint(25,81, size=10000)
df['ranking'] = np.random.randint(1,6, size=10000)
df['criteria']= df['criteria'].fillna(1)
df

month  criteria  question  age  ranking
0        11         1         2   72        1
1         4         1         5   44        2
2         8         1         7   37        1
3        11         1         3   46        3
4         9         1         5   61        2
...     ...       ...       ...  ...      ...
9995      6         1         2   73        2
9996      1         1         5   67        2
9997      8         1         5   41        1
9998      5         1         6   73        1
9999      7         1         1   34        3

[10000 rows x 5 columns]

In [3]:
mdf = df[["criteria","question", "age","ranking"]]
mdf

criteria  question  age  ranking
0            1         2   72        1
1            1         5   44        2
2            1         7   37        1
3            1         3   46        3
4            1         5   61        2
...        ...       ...  ...      ...
9995         1         2   73        2
9996         1         5   67        2
9997         1         5   41        1
9998         1         6   73        1
9999         1         1   34        3

[10000 rows x 4 columns]

In [4]:
reg = linear_model.LinearRegression()
reg.fit(mdf[["criteria","question", "age"]],mdf.ranking)

LinearRegression()

In [5]:
reg.coef_

array([0.        , 0.00194477, 0.00068578])

In [6]:
reg.intercept_

2.953857523478778

In [7]:
reg.predict([[1,3,50]])

array([2.99398083])

In [8]:
reg.predict([[1,5,70]])

array([3.01158597])

In [9]:
reg.predict([[1,7,40]])

array([2.99490212])

In [13]:
filename = "/Users/gurpreetsingh/Downloads/trained-models/linear-regression-trained-model.pkl"
# save model
pickle.dump(reg, open(filename, "wb"))
# load model
reg_store = pickle.load(open(filename, "rb"))
# you can use loaded model to compute predictions
reg_store.predict([[1,3,50]])

array([2.99398083])